pipeline {
    agent {
        docker {
            image 'openjdk:17' // You can change this to any Java version you need
            // label 'docker'     // Optional: specify a node label if needed
        }
    }

    stages {
        stage('Prepare') {
            steps {
                echo 'Creating HelloWorld.java...'
                writeFile file: 'HelloWorld.java', text: '''
public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello, World from Docker!");
    }
}
'''
            }
        }

        stage('Compile') {
            steps {
                echo 'Compiling Java program...'
                sh 'javac HelloWorld.java'
            }
        }

        stage('Run') {
            steps {
                echo 'Running Java program...'
                sh 'java HelloWorld'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
        }
    }
}
